### ISSUE TITLE
The initial HTTP response should be a 301 redirect

### ISSUE THREAD

**Issue by davidrhyswhite** [mozilla/Garmr#12]
Started using Gamr to automate some initial security testing and it's been great, picking up things that are simple for us to change. This one error however I'm not 100% certain I understand and I can't seem to find any additional information about it.

```
[Garmr.corechecks.StsRedirectCheck] Fail The initial HTTP response should be a 301 redirect (RFC violation see ).
```

It seems like there should be a URL within the RFC violation see ... 

Just wondering if this could be clarified a little in the error message?

**Comment by davehunt** [comment]
I think this might have actually been a typo introduced by @ygjb in https://github.com/mozilla/Garmr/commit/68371f6c73d9a382bf3ee66ab39f0c2796d50575#diff-b46158722764b867d91c37647532c1e8R109

**Comment by ygjb** [comment]
Indeed.  It was an error.  I will try to remember to fix it up when I
return from holidays (bonus points if someone can submit a PR that adds a
link to http://tools.ietf.org/html/rfc6797
