### ISSUE TITLE
create a release for version 0.3

### ISSUE THREAD

**Issue by vpereira** [mozilla/Garmr#14]
do you mind to create a release for the 0.3?

**Comment by mozfreddyb** [comment]
Garmr is currently abandoned.
Would you be interested in taking over the ownership, @vpereira?

I'm willing to provide some input during the transition, but you shouldn't expect a lot of support from other former developers. I recommend creating a fork and going from there.
The recently added license file should permit this.

**Comment by vpereira** [comment]
Hi Frederik, yes I would like to maintain it.. There is any reason why he
left it?

VP
Am 01.03.2016 08:47 schrieb "Frederik" notifications@github.com:

**Comment by mozfreddyb** [comment]
@vpereira The security team prioritized work around other types of automated checks (i.e. the Minion project) and Garmr was never very popular outside of our organization.

**Comment by vpereira** [comment]
@mozfreddyb well you can count on me. I'm using it in my daily work, so I could take it over.

**Comment by mozfreddyb** [comment]
@vpereira Did you create a fork that we should link to?
