### ISSUE TITLE
Example Usage in Readme

### ISSUE THREAD

**Issue by GanbaruTobi** [mozilla/Garmr#16]
Its hard to tell if this tool will fit my needs. It would be awesome to see an example output in the Readme. Greetings

**Comment by mozfreddyb** [comment]
probably not, this project is very inactive. The [Mozilla Observatory](https://observatory.mozilla.org/) does the same things and better.
You can even [run it with a cli on your own machine](https://github.com/mozilla/http-observatory-website/).

If you *do* happen to check out Garmr, you can write a pull request to modify the readme and I'll gladly accept it.
